import React, { Suspense, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Link, Route, Routes, useParams } from 'react-router-dom';
import { Canvas, useFrame } from '@react-three/fiber';
import { Environment, Float, OrbitControls, RoundedBox, Text } from '@react-three/drei';
import * as THREE from 'three';
import './styles.css';

const projects = [
  {slug:'atelier',index:'01',name:'Atelier 3D',type:'Luxury configurator',summary:'Configure a collectible watch, calculate pricing, and save a client-ready quote.',accent:'#d7b56d',metrics:['12 materials','48 combinations','Live pricing']},
  {slug:'facility',index:'02',name:'FacilityOS',type:'Digital twin operations',summary:'Inspect a connected facility, surface equipment risk, and open maintenance tickets.',accent:'#65d9c3',metrics:['24 assets','3 live alerts','99.4% uptime']},
  {slug:'space',index:'03',name:'Forma Space',type:'Collaborative room planner',summary:'Build a room layout, compare furnishing packages, and save a project estimate.',accent:'#ff9364',metrics:['18 objects','3 layouts','Auto estimate']},
  {slug:'estate',index:'04',name:'Aperture Estates',type:'Immersive real estate',summary:'Explore an architectural property, shortlist rooms, and request a private tour.',accent:'#b7a6ff',metrics:['8 residences','3D walkthrough','Tour booking']},
  {slug:'automotive',index:'05',name:'Velocity Studio',type:'Automotive configurator',summary:'Customize a performance vehicle, compare specifications, and request a dealer quote.',accent:'#ff5252',metrics:['420 hp','6 finishes','Build sharing']},
  {slug:'cloud',index:'06',name:'Nexus Cloud',type:'Infrastructure explorer',summary:'Trace service health across a 3D topology and create an incident from an affected node.',accent:'#55a8ff',metrics:['14 services','2 regions','Live incidents']},
  {slug:'museum',index:'07',name:'Aion Museum',type:'Digital collection',summary:'Inspect a curated artifact, open its story, and save it to a personal collection.',accent:'#e3c3ff',metrics:['36 artifacts','Guided stories','Saved collection']},
];

function Artifact({project,color}) {
  const group=React.useRef();
  useFrame((_,d)=>{if(group.current) group.current.rotation.y+=d*.16});
  const dark=new THREE.Color(color).multiplyScalar(.35);
  if(project.slug==='facility'||project.slug==='cloud') return <group ref={group}>{[...Array(7)].map((_,i)=><Float key={i} speed={1+i*.08}><RoundedBox args={[.65,.35,.65]} position={[(i%3-1)*1.15,Math.floor(i/3)*.8-1,(i%2-.5)*1.4]} radius={.08}><meshStandardMaterial color={i===4?'#ff5d73':color} metalness={.65} roughness={.25}/></RoundedBox></Float>)}</group>;
  if(project.slug==='space'||project.slug==='estate') return <group ref={group}><RoundedBox args={[3.6,.18,2.7]} position={[0,-1.35,0]} radius={.08}><meshStandardMaterial color={dark}/></RoundedBox><RoundedBox args={[2.1,.3,.8]} position={[0,-.55,.35]} radius={.14}><meshStandardMaterial color={color}/></RoundedBox>{[-1,1].map(x=><RoundedBox key={x} args={[.18,1.8,2.7]} position={[x*1.72,-.45,0]}><meshStandardMaterial color={dark}/></RoundedBox>)}</group>;
  if(project.slug==='museum') return <group ref={group}><mesh><torusKnotGeometry args={[1,.32,128,24]}/><meshPhysicalMaterial color={color} metalness={.85} roughness={.16}/></mesh><RoundedBox args={[1.7,.18,1.7]} position={[0,-1.55,0]} radius={.05}><meshStandardMaterial color="#24152b"/></RoundedBox></group>;
  if(project.slug==='automotive') return <group ref={group}><RoundedBox args={[3,.65,1.35]} radius={.3}><meshPhysicalMaterial color={color} metalness={.9} roughness={.12}/></RoundedBox><RoundedBox args={[1.35,.55,1.05]} position={[-.25,.52,0]} radius={.2}><meshPhysicalMaterial color="#151a22" metalness={.5}/></RoundedBox>{[-1,1].flatMap(x=>[-1,1].map(z=><mesh key={`${x}${z}`} rotation={[Math.PI/2,0,0]} position={[x*1.05,-.45,z*.68]}><cylinderGeometry args={[.36,.36,.22,32]}/><meshStandardMaterial color="#090a0d"/></mesh>))}</group>;
  return <group ref={group}><mesh rotation={[Math.PI/2,0,0]}><torusGeometry args={[1.15,.34,48,120]}/><meshPhysicalMaterial color={color} metalness={.92} roughness={.12}/></mesh><mesh position={[0,0,.12]}><cylinderGeometry args={[.88,.88,.18,64]}/><meshPhysicalMaterial color="#10131a" metalness={.8}/></mesh>{[0,1,2,3].map(i=><mesh key={i} position={[Math.sin(i*Math.PI/2)*.57,Math.cos(i*Math.PI/2)*.57,.24]}><boxGeometry args={[.04,.2,.03]}/><meshStandardMaterial color={color}/></mesh>)}</group>;
}

function Scene({project,color}) {return <Canvas camera={{position:[4,2.6,5],fov:42}} dpr={[1,1.7]}><color attach="background" args={['#080a0f']}/><ambientLight intensity={.65}/><directionalLight position={[3,5,4]} intensity={4} color={color}/><pointLight position={[-4,0,2]} intensity={10} color={color}/><Suspense fallback={null}><Artifact project={project} color={color}/><Environment preset="city"/></Suspense><OrbitControls enablePan={false} minDistance={3.5} maxDistance={8} autoRotate autoRotateSpeed={.35}/></Canvas>}

function Home(){return <main className="home"><nav><span className="brand">MERNA / IMMERSIVE LAB</span><a href="https://github.com/Mirnamo">GitHub ↗</a></nav><header><p className="eyebrow">SEVEN COMMERCIAL EXPERIENCES · ONE FULL-STACK SYSTEM</p><h1>Digital products<br/><em>you can enter.</em></h1><p className="lede">A portfolio laboratory combining 3D interaction, operational workflows, APIs, persistence patterns, and responsive product design.</p></header><section className="project-grid">{projects.map(p=><Link className="project-card" to={`/project/${p.slug}`} key={p.slug} style={{'--accent':p.accent}}><span>{p.index}</span><div className="mini-orb"/><p>{p.type}</p><h2>{p.name}</h2><strong>Open experience →</strong></Link>)}</section></main>}

function Project(){const {slug}=useParams();const project=projects.find(p=>p.slug===slug)||projects[0];const [color,setColor]=useState(project.accent);const [status,setStatus]=useState('Ready to explore');const [saved,setSaved]=useState(false);const actions={atelier:'Save configuration',facility:'Open maintenance ticket',space:'Save room plan',estate:'Request private tour',automotive:'Request dealer quote',cloud:'Create incident',museum:'Add to collection'};async function submit(){setStatus('Saving…');try{const res=await fetch(`/api/${project.slug}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({project:project.name,color,selection:'Portfolio demo'})});if(!res.ok)throw new Error();setStatus('Saved through the live API');setSaved(true)}catch{localStorage.setItem(`immersive-${project.slug}`,JSON.stringify({color,savedAt:new Date().toISOString()}));setStatus('Saved in this browser demo');setSaved(true)}}return <main className="experience" style={{'--accent':color}}><nav><Link to="/">← All projects</Link><span>{project.index} / 07</span></nav><section className="workspace"><div className="copy"><p className="eyebrow">{project.type}</p><h1>{project.name}</h1><p>{project.summary}</p><div className="metrics">{project.metrics.map(m=><span key={m}>{m}</span>)}</div><div className="controls"><label>Finish palette</label><div className="swatches">{[project.accent,'#edf2f7','#171b26','#d25d72'].map(c=><button key={c} aria-label={`Use ${c}`} onClick={()=>setColor(c)} className={color===c?'active':''} style={{background:c}}/>)}</div><button className="primary" onClick={submit}>{saved?'Saved ✓':actions[project.slug]}</button><small>{status}</small></div></div><div className="viewport"><Scene project={project} color={color}/><div className="hint">Drag to orbit · Scroll to zoom</div></div></section><section className="proof"><div><span>01</span><h3>Immersive interface</h3><p>Interactive WebGL scene with responsive camera controls, adaptive rendering, and accessible non-3D controls.</p></div><div><span>02</span><h3>Business workflow</h3><p>A project-specific action transforms the visual exploration into a realistic customer or operations outcome.</p></div><div><span>03</span><h3>Full-stack path</h3><p>Serverless API handling, validated JSON payloads, resilient browser fallback, and deployment-ready routing.</p></div></section></main>}

function App(){return <BrowserRouter><Routes><Route path="/" element={<Home/>}/><Route path="/project/:slug" element={<Project/>}/></Routes></BrowserRouter>}

createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);
